node('nodejs') {
  stage 'build'
  sh "pwd"
  sh "ls -l"
  input "begin to build??"
  openshiftBuild(buildConfig: 'nodejs-ex', showBuildLogs: 'true')
  stage 'deploy'
  openshiftDeploy(deploymentConfig: 'nodejs-ex')
}
